### ISSUE TITLE
Shape of attention map

### ISSUE THREAD

**Issue by aarontyliu** [cmsflash/efficient-attention#12]
Hi, I found the attention map computed using the [script](https://github.com/cmsflash/efficient-attention/blob/46a5f9eaf09470affb0ab30932b7748cc3c871ef/efficient_attention.py#L28) is C x C. Shouldn't it be (H x W) x (H x W) if we want spatial attention?

Thank you for any information that you can provide.

**Comment by cmsflash** [comment]
The difference is exactly why efficient attention (EA) is more efficient than the conventional dot -product attention. For why it is still exactly or approximately (in different settings) to dot-product attention, please refer to Section 3.3 of the [paper](https://arxiv.org/abs/1812.01243).
