### ISSUE TITLE
Question about the order of computation of Q K and V

### ISSUE THREAD

**Issue by chenying0722** [cmsflash/efficient-attention#14]
The order of computation for computing attention in the paper is Q(K_T)V, but the order in the coder is V(K_T)Q. 
Is it my misunderstanding or something else?
Looking forward to your reply!

**Comment by cmsflash** [comment]
The computation order is always `G = (K^T)V` and then `E = QG`. If you are asking why we put `V` on the left and `Q` on the right in the code, it is because in the paper we assume a channel-last dimension order, but PyTorch uses channel-first representation.

**Comment by chenying0722** [comment]
> The computation order is always `G = (K^T)V` and then `E = QG`. If you are asking why we put `V` on the left and `Q` on the right in the code, it is because in the paper we assume a channel-last dimension order, but PyTorch uses channel-first representation.

Thanks for your answer! I got it.
