### ISSUE TITLE
Different query positions on the same image

### ISSUE THREAD

**Issue by horanyinora** [cmsflash/efficient-attention#3]
Hello,
Thanks for the excellent work. I would like to show different attention maps produced using different query positions (reference bouding boxes). 
For example when there are three bouding boxes on the image I would like to calculate the attention w.r.t. them and show the difference. Is it possible to do this?  
![Screenshot from 2021-05-05 10-32-24](https://user-images.githubusercontent.com/20492900/117122053-5439cc00-ad8d-11eb-9cd8-39dd4aea16a2.jpg)

**Comment by cmsflash** [comment]
It is possible. You can simply multiply a specific query to the key feature map to get the query-specific weights for the entire image.
